# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1515113488);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1515113608);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1515050925);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1515051165);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1515113848);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1515051045);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1515113968);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1515113728);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1515050895);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 59);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1515078000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1515115301218");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1515117079218");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1515113475570");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1515117075570");
user_pref("browser.search.countryCode", "KR");
user_pref("browser.search.region", "KR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20171227151400");
user_pref("browser.slowStartup.averageTime", 10334);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20171227151400");
user_pref("browser.startup.homepage_override.mstone", "57.0.3");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":12,\"newElementCount\":2}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20180105);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1515050907320");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.ipc.processCount.web", 4);
user_pref("e10s.rollout.cohort", "multiBucket4");
user_pref("e10s.rollout.cohortSample", "0.955347");
user_pref("e10s.rollout.cohortSample.multi", "0.797248");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.cache.lastUpdate", 1515113491);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20171227151400");
user_pref("extensions.lastAppVersion", "57.0.3");
user_pref("extensions.lastPlatformVersion", "57.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("extensions.shield-recipe-client.user_id", "416144e3-3a8d-49f6-9ae0-a8d4533b7f40");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{97ce5417-67d5-4b79-a153-47c773f177b1}\",\"addons\":{\"disable-media-wmf-nv12@mozilla.org\":{\"version\":\"1.1\"},\"disable-js-shared-memory@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"ac9776fa-4162-4da3-a702-ac9979b9f009\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1515050982);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20171227151400");
user_pref("media.gmp-manager.lastCheck", 1515050979);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 58382);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1515111508);
user_pref("services.blocklist.clock_skew_seconds", 2102);
user_pref("services.blocklist.gfx.checked", 1515111508);
user_pref("services.blocklist.last_update_seconds", 1515111508);
user_pref("services.blocklist.onecrl.checked", 1515111508);
user_pref("services.blocklist.plugins.checked", 1515111508);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1515113453);
user_pref("toolkit.telemetry.cachedClientID", "6a0bf2c9-6c85-449d-91f4-a513ed55a4e0");
user_pref("toolkit.telemetry.previousBuildID", "20171227151400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
